### PR TITLE
feat: add stealth address validator

### PR DESCRIPTION
**Pull request by jstinhw**
Add stealth address plugin to preserve privacy of smart acount owner. 

Two modes to validate signature
- 0: signed by private key of stealth address
- 1: signed by owner's private key and secret used to generate stealth address.

Ref: https://hackmd.io/xgpI7DB_SPSyDOLsYGI1tA

### CODE REVIEW

**Comment by leekt** [comment]
Can you share the link of repository you referenced for eliptic curve library?

**Comment by jstinhw** [comment]
here's the repo: https://github.com/witnet/elliptic-curve-solidity

**Comment by KONFeature** [comment]
Any other way to perform the validation of the signature aggregation? Since, based on the witnet estimation, it would be at least 250k gas per validation
And btw, not a huge fan of the ownership changes event (triple indexed params, old one can easily be retrieved via the index on the kernel account), if we don't take in account the `sload` needing to perform

**Comment by leekt** [comment]
I'll take care about the sload in separate PR for gas saving

@jstinhw
> Any other way to perform the validation of the signature aggregation? Since, based on the witnet estimation, it would be at least 250k gas per validation

can you confirm there aren't any other way for signature aggregation?

**Comment by jstinhw** [comment]
@KONFeature @leekt Thanks for the suggestion. I found another way to do verification which can reduce the gas to 1/6 compared to the aggregated signature. The tradeoff is that it relies on zk proof verification on-chain. Here's more information about the [scheme](https://hackmd.io/xgpI7DB_SPSyDOLsYGI1tA?view#c-Masked-Message-Signature)

**Pull request merged**
